### ISSUE TITLE
[v3] Proposal of provide at least empty traits for interfaces.

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zend-servicemanager#10]
Actually it's difficult to make changes on interface definitions and preserve the backward compatibility at the same time.

Abstract classes are more flexible and allow more code changes without break the compatibility while still preserving the same signature as before. However Abstract classes does not allow composition (multi inheritance)

I propose to provide at least an empty trait for each defined interface and suggest to the user to always use that trait in their code. Traits allow us to provide small changes (usually proxy methods) while preserve the compatibility with existing implementations.

Implement this code style guideline implies the following:

* Existing traits which name match with the interface are reserved for provide the most basic implementation (When a set of traits provide alternative implementations about the same interface their names must not match with the interface name)

* Code on traits should must rely only on the interface public methods and don't provide new methods don't exists on the interface.

* protected and private methods are not allowed. Traits must be minimal.

**Comment by bakura10** [comment]
Should be closed @weierophinney ?
