### ISSUE TITLE
BC break: not able to find ServiceManager named service

### ISSUE THREAD

**Issue by metanav** [zendframework/zend-servicemanager#101]
After upgrade ( I am not sure it's zend-mvc or zend-servicemanager), the code below is throwing exception:
Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for ServiceManager 

[Factory/AuthControllerFactory](https://github.com/zfcampus/zf-oauth2/blob/master/src/Factory/AuthControllerFactory.php#L22)
```
$services = $controllers->getServiceLocator()->get('ServiceManager');
```

When the code is changed to:
```
$services = $controllers->getServiceLocator();
```

It works but I am not sure if this is backward compatible.

**Comment by weierophinney** [comment]
Plugin managers receive the parent service manager, and that's what you're retrieving when you call `getServiceLocator()`; calling `get('ServiceManager')` was actually redundant!

As such, while this might be a minor BC break, it's also helping you discover a problem in your code - I'd update your code!

**Comment by metanav** [comment]
So you will be updating the code in [Factory/AuthControllerFactory](https://github.com/zfcampus/zf-oauth2/blob/master/src/Factory/AuthControllerFactory.php#L22) (which is part of zfcampus/zf-oauth2) or I should create a PR?

**Comment by weierophinney** [comment]
Ouch! Missed that this was part of zf-oauth2! Yes, please create a PR!

**Comment by metanav** [comment]
I created a PR zfcampus/zf-oauth2#134. I think we need to  update composer.json in zfcampus/zf-oauth2 to get rid of failing tests.
