### ISSUE TITLE
How to create ServiceManager object for both V2 and V3

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-servicemanager#102]
I want to support both but the constructor signatures are different
```php
ServiceManager::__construct(ConfigInterface $config = null);
ServiceManager::__construct(array $config = []);
```
and now I am creating ServiceManager:
```php
$config = [];
new ServiceManager(new Zend\ServiceManager\Config($config)); // does not work for V3
new ServiceManager($config); // does not work for V2
```
maybe I am missing something?

**Comment by svycka** [comment]
I have looked more into ConfigInterface for both versions and found a way but not sure it is the recomended one :) can someone confirm?

```php
// create container
$container = new ServiceManager();
// pass config
$containerConfig = new Config($config['dependencies']);
$containerConfig->configureServiceManager($container);
```
I think this should work with both versions

**Comment by weierophinney** [comment]
@svycka That last example is exactly how we tackled it in the refactors on the various components. :+1:

You can even get rid of the transient instance:

```php
$container = new ServiceManager();
(new Config($config))->configureServiceManager($container);
```
