### ISSUE TITLE
Initializer with returning value

### ISSUE THREAD

**Issue by marcosh** [zendframework/zend-servicemanager#108]
I think it could be useful to allow the `InitializerInterface` to return a new instance of the object it is initializing.

For example we could have an initializer like

    function ($container, $instance) {
        if (/*some condition on $instance*/) {
            return new OtherClass($instance);
        }
    }

This could be useful, for example, for decorating a set of objects based on an interface they are implementing.

Moreover, this would not influence the current behaviour of the initializers.

Is there any reason not to do this I am not seeing?

**Comment by snapshotpl** [comment]
@marcosh that's why we have delegators http://zendframework.github.io/zend-servicemanager/delegators/

**Comment by marcosh** [comment]
@snapshotpl thanks for your answer. I know about delagators, but, as far as I know, you can use them to override single explicit classes. That is, you have to know which classes you are overriding at compile time. I would like to have that at run time...

To be more explicit, I would like to override every class implementing an interface `I`.

I would like to do have an initializer like

```
function ($container, $instance) {
    if ($instance instanceof I) {
        return $somethingElse;
    }
}
```

If this is actually possible using delegators, could you give me an hint on how?

**Comment by Ocramius** [comment]
> If this is actually possible using delegators, could you give me an hint on how?

Not really supported

**Comment by marcosh** [comment]
Thanks for your reply, @Ocramius. Since what I'd like to achieve is not possible using delegators, would it make sense to alter a bit how initializers work, just using their return value, to do it? It shouldn't break anything and it would allow use cases that are not currently possible (at least I think so...)

**Comment by Ocramius** [comment]
>  just using their return value, to do it?

That would change initializers massively, no?

**Comment by marcosh** [comment]
It would allow to use initializars for other use cases and to do more things with them. The one already present would work exactly as they do now, so nothing would break. Maybe the name "initializers" itself would not be still very appropriate...

To be clear, what I had in mind was something like the following (it could probably be polished) in the `doCreate` method of the `ServiceManager` class:

```
foreach ($this->initializers as $initializer) {
    $newObject = $initializer($this->creationContext, $object);

    if (!is_null($newObject)) {
        $object = $newObject;
    }
}
```

I guess that the question now is: is this something that has a reason to be? Or is it more reasonable to leave this out and do not address the possible use cases that this would allow to solve?

**Comment by danizord** [comment]
In delegators, you get the requested instance by calling the given callable. Would not it fix your problem?

**Comment by Ocramius** [comment]
@danizord he'd still need it for a set of services, not just a single service

**Comment by danizord** [comment]
Ha yeah :sweat_smile:
