### ISSUE TITLE
Self destructing factories. Possible performance tip.

### ISSUE THREAD

**Issue by Maks3w** [zendframework/zend-servicemanager#11]
Many factories are used for to be called once, (EventManager, Mailer)

I suggest that factories could be removed from the factory index after invoke and following calls return the original object instead.

/cc @bakura10 @weierophinney

**Comment by bakura10** [comment]
You mean never storing the factory object and always rebuilding it? Hmm why not, although I'm not sure the memory impact of storing a factory is huge, considering it does not have any properties.

**Comment by Maks3w** [comment]
I consider after the first call to that factory, store the built object, destroy the factory, return the built object on consecutive calls.

**Comment by Maks3w** [comment]
The idea behind this it's to reduce the number of lookups while the application request is going forward.

**Comment by weierophinney** [comment]
We already store created instances, meaning no factory lookup on subsequent
requests. Additionally, in cases where build() might be used, this could
lead to inconsistent state...

**Comment by bakura10** [comment]
Close?
