### ISSUE TITLE
v3 performance while registering services factories and aliases

### ISSUE THREAD

**Issue by pine3ree** [zendframework/zend-servicemanager#122]
Working with zend-expressive i found out that migrating to a newer version that included servicemanage 3 the very same test app was much slower. This occurred when registering all zend-form helper plugins.

https://github.com/zendframework/zend-expressive-zendviewrenderer/issues/25
https://github.com/zendframework/zend-form/issues/76

So i decided to prepare and run 2 simple test scripts whose only purpose is to register all zend-form view helpers using zend-servicemanager v2 and v3 and explain the issue here as I believe this repo is more appropriate for this.

##### v3 test: zend-form configuration time ~ 22 ms (PHP 7.0), ~52-70 ms (PHP 5.6)
```
cd /my/test/path/sm3
composer require zend-servicemanager:3.0.*
composer require zend-i18n
composer require zend-form
composer require zend-view
```

```php
<?php
// file /my/test/path/sm3/test.php
require 'vendor/autoload.php';

use Zend\ServiceManager\ServiceManager;
use Zend\ServiceManager\Config;
use Zend\I18n\View\HelperConfig as I18nViewHelperConfig;
use Zend\Form\View\HelperConfig as FormViewHelperConfig;
use Zend\View\HelperPluginManager;

$serviceManager = new ServiceManager();
$helperManager  = new HelperPluginManager($serviceManager);

(new I18nViewHelperConfig())->configureServiceManager($helperManager);

$t0 = microtime(true);
(new FormViewHelperConfig())->configureServiceManager($helperManager);
$ms = 1000 * round(microtime(true) - $t0, 5) . ' ms';

echo 'zend-servicemanager-v3 => ' . $ms . PHP_EOL;
```

```
$ php70 test.php # ~ 22 ms
$ php56 test.php # ~52-70 ms
```

##### v2 test: zend-form configuration time < 2ms (PHP 7.0), ~7-9 ms (PHP 5.6)
```
cd /my/test/path/sm2
composer require zend-servicemanager:2.7.*
composer require zend-i18n
composer require zend-form
composer require zend-view
```

```php
<?php
// file /my/test/path/sm2/test.php
require 'vendor/autoload.php';

use Zend\ServiceManager\ServiceManager;
use Zend\ServiceManager\Config;
use Zend\I18n\View\HelperConfig as I18nViewHelperConfig;
use Zend\Form\View\HelperConfig as FormViewHelperConfig;
use Zend\View\HelperPluginManager;

$serviceManager = new ServiceManager();
$helperManager  = new HelperPluginManager();
$helperManager->setServiceLocator($serviceManager);

(new I18nViewHelperConfig())->configureServiceManager($helperManager);

$t0 = microtime(true);
(new FormViewHelperConfig())->configureServiceManager($helperManager);
$ms = 1000 * round(microtime(true) - $t0, 5) . ' ms';

echo 'zend-servicemanager-v2 => ' . $ms . PHP_EOL;
```

```
$ php70 test.php # < 2ms
$ php56 test.php # ~7-9 ms
```

All the installed packages have the same version excluding zend-servicemanager

any hint/help?

could this performance degradation be related to ServiceManager 3 configure() method, involving rewriting the alias arrays and performing inner tests on existing keys and called for every registered alias?

or simply is there something wrong in my setup (all this started when overwriting/delegating a new HelperPluginManagerFactory/DelegatorFactory in zend-expressive https://github.com/zendframework/zend-expressive-zendviewrenderer/issues/25
https://github.com/zendframework/zend-form/issues/76 my last comments)

kind regards

PS
forgot to mention that in the zend-expressive test app I obviously use zend opcode cache ext.

**Comment by Ocramius** [comment]
Could you please convert this into a benchmark PR? We have a dedicated dir
for it...

**Comment by pine3ree** [comment]
@Ocramius @weierophinney 

Thank You Marco, writing the benchmark helped me to the right direction for a solution (or ate leats for the probable cause)

I found out that the performance degradation appears more evidently when aliases of aliases are defined and only when using setAlias(). If using ServiceManager::configure for an array of aliases there is no evident degradation.

Indeed  configureServiceManager() method in various HelperConfig classes loop through $config['aliases'] and $config['factories'] calling setAlias and setFactory instead of configure (I haven't checked if this was done to maintain bakckwards compatibility with previous versions)

the bench test i used
```php
<?php

namespace ZendBench\ServiceManager;

use PhpBench\Benchmark\Metadata\Annotations\Iterations;
use PhpBench\Benchmark\Metadata\Annotations\Revs;
use PhpBench\Benchmark\Metadata\Annotations\Warmup;
use Zend\ServiceManager\ServiceManager;

/**
 * @Revs(10)
 * @Iterations(5)
 */
class ManyAliasesBench
{
    /**
     * @var ServiceManager
     */
    private $sm;

    private $aliases_10;
    private $aliases_100;

    public function __construct()
    {
        $this->sm = new ServiceManager([
            'factories' => [
                'fooFactory' => BenchAsset\FactoryFoo::class,
            ],
        ]);

        $this->aliases_10   = $this->createAliases(10);
        $this->aliases_100  = $this->createAliases(100);
    }

    private function createAliases($n)
    {
        $aliases = [];
        for ($i = 1; $i < $n; $i++) {
            $aliases['foo_' . $i] = 'fooFactory';
            $aliases['bar_' . $i] = 'foo_' . $i; // alias of alias
        }

        return $aliases;
    }

    public function benchConfigure10Aliases()
    {
        $sm = clone $this->sm;

        $sm->configure(['aliases' => $this->aliases10]);
    }

    public function benchSet10Aliases()
    {
        $sm = clone $this->sm;

        foreach ($this->aliases_10 as $alias => $target) {
            $sm->setAlias($alias, $target);
        }
    }

    public function benchConfigure100Aliases()
    {
        $sm = clone $this->sm;

        $sm->configure(['aliases' => $this->aliases100]);
    }

    public function benchSet100Aliases()
    {
        $sm = clone $this->sm;

        foreach ($this->aliases_100 as $alias => $target) {
            $sm->setAlias($alias, $target);
        }
    }
}
```

kind regards

**Comment by pine3ree** [comment]
@Ocramius @weierophinney 

I can confirm that changing Zend\Form\View

**Comment by Ocramius** [comment]
@pine3ree nice findings! Does the removal of the indirection fix the performance issue?

**Comment by pine3ree** [comment]
Yes but unfortunately that change breaks compatibility with servicemanager v2 (2.7.x) which does not possess a configure() method. v3 setALias, setFactory..etc etc methods are proxy to the new configure() method. This new method works with array parameters representing a global $config for the manager itself. To maintain compatibility the setters now proxy to configure, sending a partial/single service-class value $config to it.

**Comment by weierophinney** [comment]
You could add a test for the configure method and, if present, use it, and
if not, call the other methods...

**Comment by pine3ree** [comment]
@Ocramius @weierophinney 

Maybe #77 is not very elegant but it works. 
Should I add a similar patch for zend-i18n View\Helper\Config?

Nevertheless I believe that loop calls to set(Alias|Factory|...) should not cause such performance overhead but i see no other solution than going back to single method in body implementation.
 
kind regards

**Comment by pine3ree** [comment]
@weierophinney #77 :-) already added a PR! kind regards.

**Comment by pine3ree** [comment]
...added the same patch for zend-i18n https://github.com/zendframework/zend-i18n/pull/47.

I got back my 12-20 ms execution time: I hope I will not bother you anymore (for the rest of the week).

kind regards and... thank You.

ps
since configure is part of the public interface of sm3 I used method_exists(...) instead of is_callable([$obj, 'method']) ...

**Comment by pine3ree** [comment]
fixed by :
https://github.com/zendframework/zend-form/pull/77
https://github.com/zendframework/zend-i18n/pull/47
