### ISSUE TITLE
AbstractPluginManager raises deprecation warning (possible bug?)

### ISSUE THREAD

**Issue by MaDKaTZe** [zendframework/zend-servicemanager#131]
As many of you know, migration to Zend\ServiceManager 3.0 isn't straightforward as it includes many BC breaks. This includes the removal of **ServiceLocatorAwareInterface**. 

This is the place to ask if this is an actual bug or just early notice, but in version 2.7.6 of **zend-servicemanager**, the `Zend\ServiceManager\AbstractPluginManager` tends to implement the interface above, causing an E_WARNING to be thrown during it's initialization.

 Is it possible to create a fix for it or I should consider migration to version 3.0 of the module, when possible?

**Comment by weierophinney** [comment]
@MaDKaTZe The zend-mvc 2.7 series fixes this issue (see zendframework/zend-mvc#88) by injecting the parent locator during instantiation, and a patch applied for 2.7.4 (see zendframework/zend-mvc#114) ensured that if a service locator was already present in a plugin manager, it would not attempt the injection — and therefor no longer raise a deprecatoin message.

The only reason you should see such messages at this point are for custom plugin manager implementations; no plugin managers implemented by ZF should cause the issue to be raised any longer.
