### ISSUE TITLE
ServiceLocator instead of Container

### ISSUE THREAD

**Issue by jg-development** [zendframework/zend-servicemanager#133]
Hi,

I want to migrate our Application from Zend 2 to Zend 3. At first only the servicemanager.
We want to use the new "build" method for creating objects with options.

The new system always uses the "__invoke" method to call the factory. This is fine by us, but the signature has now the "ContainerInterface" instead of the "ServiceLocatorInterface".
The "ContainerInterface" does not have the "build" method. The "$container->build('Foo')" works (Its always a servicelocator), but the IDE shows a warning.

I think we need an FactoryInterface with the ServiceLocator inside the __invoke method.
Is this possible to implement with the next version.

Greetings Jan

**Comment by weierophinney** [comment]
`build()` is used for plugin managers, primarily, and essentially an internal detail of how the service is created; it is guaranteed to always return a new instance. The ServiceManager and plugin managers use `build()` to create the instance, but `get()` then decides whether or not to cache it, based on whether or not the service is marked as *shared*.

If you want a new instance, you should mark the service as `shared => false`, and call `$container->get()` within your factories.

Marking a service as not shared:

```php
[
    'shared' => [
        ServiceName::class => false,
    ]
]
```
