### ISSUE TITLE
ServiceManager Initializers seems not to work on Controller

### ISSUE THREAD

**Issue by bricks81** [zendframework/zend-servicemanager#138]
ZF3 zend-servicemanager v3.1.1
I've tried to add an Initializer which will not be called for the controller:

Zend\ServiceManager\ServiceManager on Line: 761 (doCreate)

```php
foreach ($this->initializers as $initializer) {

    if(!is_array($object)){
    	if('Application\Controller\IndexController' == get_class($object)){
    		die(var_dump(get_class($initializer)));
    	}        		
    }
    $initializer($this->creationContext, $object);
}
```

Returns:

```text
Warning: get_class() expects parameter 1 to be object, array given in vendor\zendframework\zend-servicemanager\src\ServiceManager.php on line 764
bool(false) 
```

**Comment by weierophinney** [comment]
Can you provide the initializer, please? I suspect you may be using the v2 signature; initializers changed signature with v3.

**Comment by bricks81** [comment]
Hi, here ist he initializer and the configuration.

 

 

Von: weierophinney [mailto:notifications@github.com] 
Gesendet: Sonntag, 17. Juli 2016 00:44
An: zendframework/zend-servicemanager <zend-servicemanager@noreply.github.com>
Cc: Sven <github@28-n-half.de>; Author <author@noreply.github.com>
Betreff: Re: [zendframework/zend-servicemanager] ServiceManager Initializers seems not to work on Controller (#138)

 

Can you provide the initializer, please? I suspect you may be using the v2 signature; initializers changed signature with v3.

**Comment by weierophinney** [comment]
I need some more information:

- Please provide the result of running `composer show` in your project root; feel free to remove any sensitive entries, but it *must* show the zendframework components and their versions.
- The code or configuration you're using to add the initializer to the controller plugin manager.
- Is `ConfigServiceAwareInterface` in the `BricksConfig` namespace?

Thanks in advance!

**Comment by weierophinney** [comment]
Closing due to lack of response from the author.
