### ISSUE TITLE
Add more tutorial documentation for AbstractFactory vs Factory

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-servicemanager#148]
Essentially, we have this:

| Approach | Pros | Cons |
| --- | --- | --- |
| Abstract factory | One-time setup | Performance; discovery of code responsible for creating instance |
| Factory | Performance; explicit mapping to factory responsible | Additional (duplicate) setup |

I think denoting both approaches, along with their benefits and drawbacks, allows developers to choose which approach makes the most sense for their own application needs.

**Comment by weierophinney** [comment]
See #150 :smile:
