### ISSUE TITLE
Creation options auto passing empty array breaks Boolean Filter

### ISSUE THREAD

**Issue by amcsi** [zendframework/zend-servicemanager#159]
With the change of #127 empty creation options are now passed as empty arrays rather than NULL to the constructors of services.
This results in a breaking change affecting the Zend\Filter\Boolean.

https://github.com/zendframework/zend-filter/blob/master/src/Boolean.php#L64

Before the PR, NULL would have been passed to the constructor by default, defaulting the "type" value to TYPE_PHP which would do regular PHP-style casts. Now that an empty array is passed instead, it assumes 0 as the type and keeps it there, because there is no 'type' override in the "creation options".

AKA this gets executed:
https://github.com/zendframework/zend-filter/blob/master/src/Boolean.php#L73
https://github.com/zendframework/zend-filter/blob/master/src/Boolean.php#L95
https://github.com/zendframework/zend-filter/blob/master/src/Boolean.php#L104
https://github.com/zendframework/zend-filter/blob/master/src/Boolean.php#L117

Setting the 'type' to 0, and as such _everything_ is casted to TRUE due to 'casting' being TRUE by default

https://github.com/zendframework/zend-filter/blob/master/src/Boolean.php#L289

So even e.g. NULL gets filtered to TRUE

EDIT: This issue was FIXED in this PR #164 and was released in version 2.7.8

**Comment by faoliva** [comment]
Yes I detect same issue too!
When forms are created automatically by annotation builder, the issue reveals itself.

Thanks amci!

**Comment by PoetikDragon** [comment]
Having this same problem! Thank you amcsi for the fix, hopefully it will be accepted soon.

**Comment by Aeolun** [comment]
@amcsi Would it be better to fix the issue in the place where it actually happens? I'd guess the fact that null is suddenly `[]` seems like it might cause issues in more than just this one place.

That said, I also had issues with only the `Boolean` filter, so who know.

**Comment by amcsi** [comment]
@Aeolun I actually agree, I just thought that there was some good reason they wanted to make sure that creation options are `[]` in #127, but if not, then yes it would be better to actually change that. Perhaps ->setCreationOptions(null) would work

**Comment by amcsi** [comment]
@Aeolun I have created this fix here: #159

**Comment by Koopzington** [comment]
Found out that i'm having the same issue using the ToNull filter today.

**Comment by amcsi** [comment]
Closing this, because the Service Manager fix #164 has been merged.

**Comment by amcsi** [comment]
Unfortunately by regression from #205, I'm reopening this ticket

**Comment by weierophinney** [comment]
Fixed with #210.
