### ISSUE TITLE
AbstractPluginManager alias is not resolved with autoAddInvokableClass

### ISSUE THREAD

**Issue by jkromski** [zendframework/zend-servicemanager#165]
Hi
My config

```
'source_manager' => [
         'aliases' => [
            'experiences' => Source\Experiences::class,
        ]
    ]
```

My manager class: 

```
class PluginManager extends AbstractPluginManager
{
    protected $instanceOf = SourceInterface::class;
}
```

It does not contain any factory or invokable. As my plugin manager had flag autoAddInvokableClass set to true I was expecting that at first alias will be resolved and invocable will be created on runtime when I call:
`$manager->get('experiences');`

current behaviour is fine for ServiceManager as it does not have autoAddInvokableClass flag but AbstractPluginManager should have has() method adjusted same as it is done with get() method

**Comment by weierophinney** [comment]
> AbstractPluginManager should have has() method adjusted same as it is done with get() method

Except that the `get()` method **uses** `has()` to determine if the service exists, and only if it doesn't checks to see if it is known class and the `autoAddInvokableClass` flag is true before it determines if an error exists.

We could potentially invert the logic, and have `has()` do the `InvokableFactory` injection; I'll look into it shortly.

**Comment by weierophinney** [comment]
Closing; we already have a test, `ZendTest\ServiceManager\AbstractPluginManagerTest::testAutoInvokableServicesAreNotKnownBeforeRetrieval`, which asserts that the behavior is currently *intentional*; changing it at this point would be a BC break.
