### ISSUE TITLE
Test failure with 7.1.2RC1

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-servicemanager#177]
Discovered in Fedora QA after update from 7.1.1 to 7.1.2RC1
`
PHP Fatal error:  Declaration of Zend\Form\FormElementManager\FormElementManagerTrait::get($name, $options = Array, $usePeeringServiceManagers = true) must be compatible with Zend\ServiceManager\AbstractPluginManager::get($name, ?array $options = NULL) in /usr/share/php/Zend/Form/FormElementManager/FormElementManagerV3Polyfill.php on line 26`

This seems to affect various ZF component
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-mvc-plugin-prg?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-mvc-plugin-identity?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-mvc-plugin-flashmessenger?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-captcha?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-form?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-test?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-router?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-validator?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-authentication?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-session?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-log?collection=f26
* https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-mvc-plugin-fileprg?collection=f26

PHP Release Managers have been informed about this, under investigation to see if must be fixed in PHP 7.1.2 or if this is a valid error.

Bug open mostly for your information, please raise your voice (php internals ML seems a good place)

P.S. single bug for this component, other failure may be unrelated, but I don't plan to open a bug tracker against each component.

**Comment by remicollet** [comment]
FYI, the RM choose to revert the guilty change, so 7.1.2RC1 (which will be announced later today) will work as expected (see above link, back to green in Fedora QA, 7.1.2-0.1.RC1 was the old tag, 7.1.2-0.2.RC1 is the new one))

So closing this "for information" issue, and I will continue to monitor future changes.

**Comment by Ocramius** [comment]
Ref: https://github.com/php/php-src/commit/648238da5c45bdf2c65d856b533f9a2534864ba2
Ref: https://github.com/php/php-src/commit/46de334452683953425b25fc0451649eaa6059fe
