### ISSUE TITLE
[Question] PSR-11 What are the plans for SM?

### ISSUE THREAD

**Issue by xorock** [zendframework/zend-servicemanager#181]
Hello everyone.
We all know that SM is critical component for Zend Framework \ Expressive with lot of dependencies to Interop\Container\ContainerInterface. Could You please clarify, what is the future of SM now, when PSR-11 was accepted and there is new namespace Psr\Container?

Thank You.

**Comment by weierophinney** [comment]
You missed the open PR about this: #180. :smile:
