### ISSUE TITLE
generate-factory-for-class should add logging if LoggerAwareTrait implemented

### ISSUE THREAD

**Issue by zippy1981** [zendframework/zend-servicemanager#183]
I propose the following changes to [FactoryCreatorCommand](https://github.com/zendframework/zend-servicemanager/blob/master/src/Tool/FactoryCreatorCommand.php).

1. See if the class uses a trait called `LoggerAwareTrait`
1. See if that trait has a method called `setLogger()`
1. If so, the invoke member of the factory it generate should look something like:

    public function __invoke(ContainerInterface $container, $requestedName, array $options = null)
    {
        return (new IndexController())->setLogger($container->get('log'));
    }

You could whitelist a bunch of known PSR7 compatible LoggerAwareTrait's but this is most future proof. You could add a flag to prevent logger injection in the factory if you feel that is a concern.

**Comment by asgrim** [comment]
This should be done explicitly with a delegator factory. Basically what you're proposing is what initializers used to do, but because they ran on every service creation, it's not so great on performance.

**Comment by asgrim** [comment]
Have a read up on: https://ocramius.github.io/blog/zend-framework-2-delegator-factories-explained/

**Comment by GeeH** [comment]
This is a userland implementation and I don't see this being implemented in the component .
