### ISSUE TITLE
AbstractPluginManager::__construct now expects a Interop\Container\ContainerInterface instance representing the parent container

### ISSUE THREAD

**Issue by Synchro** [zendframework/zend-servicemanager#190]
My current code using Zend_Feed has started throwing this error. I see mentions of having to do this in #100, but [the docs](https://docs.zendframework.com/zend-feed/reader/#extending-feed-and-entry-apis) give no idea what I'm supposed to do, and none of the examples do it. This is my code:

	$extensions = new ExtensionPluginManager;
	$extensions->setInvokableClass('Media\Entry', MyApp\RSS\Media\Entry::class);
	Reader::setExtensionManager(new ExtensionManager($extensions));
	Reader::registerExtension('Media');

I don't understand what's required here because I don't have a container to give to `ExtensionPluginManager` - the extension is attached statically to `Reader`. Can I make it be quiet by doing something like:

    $extensions = new ExtensionPluginManager(new SomeDummyContainerClass);

BTW thanks for fixing [Zend_Feed #30](https://github.com/zendframework/zend-feed/issues/30), which involves the same code.

**Comment by Synchro** [comment]
Any pointers on this? As far as I can see it's still undocumented and I have no idea how I can create / get hold of a container to give it.

**Comment by Synchro** [comment]
Any chance of some attention to this? BC breaks are fine, but undocumented BC breaks are a bit unsporting!

**Comment by weierophinney** [comment]
This is covered in the changelog for 2.6.0: https://github.com/zendframework/zend-feed/releases/tag/release-2.6.0

**Comment by Synchro** [comment]
Thanks, that helps a bit - but how should I pass in my extension - `setInvokableClass` apparently doesn't exist in `StandaloneExtensionManager` as it did in `ExtensionPluginManager`?

```php
$extensions = new StandaloneExtensionManager;
$extensions->setInvokableClass('Media\Entry', MyApp\RSS\Media\Entry::class);
Reader::setExtensionManager(new ExtensionManager($extensions));
Reader::registerExtension('Media');
```
results in:

    Error: Call to undefined method Zend\Feed\Reader\StandaloneExtensionManager::setInvokableClass()

The junglebooks example code in the docs still describes the old way that doesn't work.

**Comment by Xerkus** [comment]
https://docs.zendframework.com/zend-servicemanager/migration/#invokables
Invokables were removed, in v3 you should use InvokableFactory and aliases.

**Comment by Synchro** [comment]
After lots of going in circles, I've got this working. The whole servicemanager thing seemed like overkill for something that should be very simple (I'm not managing a service, I'm parsing RSS), so I'm thankful I didn't need to go there.

I saw the docs comment about copy/pasting the `StandaloneExtensionManager` class (though make sure you get the latest as it's changed a lot since 2.6), so I've done that (in my own namespace) and added my extension into its private list manually:

```php
namespace MyApp\RSS;

use Zend\Feed\Reader\Extension;
use Zend\Feed\Reader\ExtensionManagerInterface;

class StandaloneExtensionManager implements ExtensionManagerInterface
{
    private $extensions = [
        'Atom\Entry' => 'Zend\Feed\Reader\Extension\Atom\Entry',
        'Atom\Feed' => 'Zend\Feed\Reader\Extension\Atom\Feed',
...
        'Media\Entry' => Media\Entry::class //My extension
    ];
...
```

then I instantiate the manager and register the extension:

```php
Reader::setExtensionManager(new MyApp\RSS\StandaloneExtensionManager);
Reader::registerExtension('Media');
```

and I'm happy to say that works. It would be great if the docs could be updated with an example like this rather than the broken one that's there now. Can you point me at the right repo for that?

**Comment by froschdesign** [comment]
@Synchro 
> Can you point me at the right repo for that?

See: https://github.com/zendframework/zend-feed/issues/44
