### ISSUE TITLE
Factory relying on container keys

### ISSUE THREAD

**Issue by marcosh** [zendframework/zend-servicemanager#194]
I often find myself writing factories which just retrive things from the container to pass them as parameter of the object that is being built.

For examples, if we have a class

```php
class Foo {
    public function __construct(Bar $bar, Baz $baz) {...}
}
```

my factory looks like

```php
class FooFactory {
    public function __invoke(ContainerInterface $container) {
        return new Foo(
            $container->get(Bar::class),
            $container->get(Baz::class)
        );
    }
}
```

Now we have `ReflectionBasedAbstractFactory` which can help us avoid writing all these factories, but, IMHO it has two drawbacks:
- it relays on Reflection, which makes it slow
- it forces you to use class names as container keys (not that it is a bad thing, but sometimes it could be limiting)

I propose to add another factory that looks something like this (the name probably needs to be changed)

```php
class ContainerKeyFactory
{
    /**
     * @var array
     */
    private $dependencyKeys;

    private function __construct() {}

    public static function withDependencies(string ... $dependencyKeys) {
        $instance = new self();
        $instance->dependencyKeys = $dependencyKeys;
        return $instance;
    }

    public function __invoke(ContainerInterface $container, string $requestName) {
        return new $requestName(
            ... array_map(
                function (string $key) use ($container) {
                    return $container->get($key);
                },
                $this->dependencyKeys
            )
        );
    }
}
```

which could then be used as

```php
$dependencies = [
    'factories' => [
        Foo::class => ContainerKeyFactory::withDependencies(Bar::class, Baz::class)
    ]
]
```

This solves the point I mentioned above and it provides a super fast way to create easy factories. The only drawback with respect to `ReflectionBasedAbstractFactory` is that you have to explicitely declare the keys used to retrieve the dependecies.

What do you think?

**Comment by weierophinney** [comment]
There's already a solution that does this: `ConfigAbstractFactory`: https://docs.zendframework.com/zend-servicemanager/config-abstract-factory/

Essentially, you map your service to that factory, and then add configuration that maps the service name to a list of services to inject. It's faster than the `ReflectionBasedAbstractFactory`, and gives the flexibility to provide specific service names, as you detailed above.

**Comment by marcosh** [comment]
Thanks a lot! Sorry for opening an issue for something that was already there

**Comment by Ocramius** [comment]
One thing that I could use though, is a replacement for an
`InvokableFactory` that just tries a brutal lookup by constructor argument
hint (`ConstructorReflectionFactory`?). 🤔

**Comment by weierophinney** [comment]
@Ocramius That's what `ReflectionBasedAbstractFactory`does when you map it as the factory for a service. It doesn't need to be used as an abstract factory; all abstract factories follow the same signature as normal factories. :wink:

**Comment by Ocramius** [comment]
Oooh shiny! I didn't know this: that's awesome!

Functional interfaces FTW!
