### ISSUE TITLE
Discussion: Revoke deprecation of invokables

### ISSUE THREAD

**Issue by fhein** [zendframework/zend-servicemanager#223]
Please read #222 first.

If you can agree not to deprecate aliases and you accept the performance of alias resolution as of #221, I'd propose to revoke the deprecation of invokables.

Invokables as of ZF2 were created at the cost of new(). Use of InvokableFactory requires to instantiate the the factory (once, hopefully, did not look at that yet) which then instantiates the invokable. That is quite more expensive.

As aliases do not have negative performance impact any longer, it is ok to alias an invokable if you need a name for reference other than the class name (which would work out of the box).

What to do with InvokableFactory which was no longer required? As the fan of BC I am I see, two options on how to proceed:

1.  Do nothing. They continue to work as documented (somewhat slower (but not critical) than invokables)
2. Continue support of InvokableFactory in the API (config) but translate them internally to an invokable and an alias to it, if the key for the InvokableFactory is not a class name. 

The current implementation silently translates invokable definitions to InvokableFactory + alias.

Let's discuss, please. I offer fast implementation. Including benchmarks. 

The resolution precedence of invokables would be lower than any factory but higher than aliases resulotion.

If you have concerns about performance because of abstract factories, I will address that also in #221.

The benefit if consensus regarding this, #221 and #222 would be significant performance gain. (significant = 5-10% at least).

**Comment by Ocramius** [comment]
Closing as per https://github.com/zendframework/zend-servicemanager/pull/254#issuecomment-364026562
