### ISSUE TITLE
Feature request: ServiceManager provided name management

### ISSUE THREAD

**Issue by fhein** [zendframework/zend-servicemanager#224]
If ServiceManager gets configured via configuration file, everything currently is ok (except alias defintions which can not get resolved, see #222). 

But if I register services and factories by name, I have to take care programmatically, that the service name is unique and does not overwrite any service name that's already registered. The allowOverride setting can help during the debug phase, but I would like to have an option to omit that debugging step.

So I propose, that setService, setFactory (maybe setAlias) have special behavior if you set a service without a name. Here's a pseudo code example on how that could implemented without BC break.

    public setService($p1, $p2 = null) {
        if ($p2 === null) {
            $p2 = $p1;
            $p1 = unique id;
        }
        register sevice as usual;
        return $p1;
    }

This is just to explain semantics. The example is not optimized for performance.

If you supply key and value nothing changes (that's the BC compliance case). If you supply key only, 
key is taken as value and a key gets created, which is granted to be unique. 

In any case this key get's returned for further referral. Example:

    $handle = $servicemanager->setService($myService);
    ...
    code / code / more code 
    ...
    $service = $servicemanager->getService($handle);
     // do fantastic things with the retrieved service
     // while being sure that it is the service you wanted 

Considerations:

You may want to store ids which are automatically generated in a file and reuse it on the next run/request. id generation therefore has to grant, that for a particular service the unique id generated does not change. Otherwise you'd have to manage dynamics at the cost of dynamics.

There are standards on how to handle this. I offer to implement that fast respecting that constraint. Benchmarks included.

Benefit would be, that you could be sure, that your registered service does not overwrite an existing service configuration without intent.

**Comment by kynx** [comment]
I’m struggling with this one. It looks like you are passing the (auto-generated) $handle around so you can fetch it again from SM? Why not pass $myService around instead and leave SM alone?

**Comment by fhein** [comment]
When using setService to programmatically set a service, you have to provide a unique name in order to retrieve it again.

I you are using a FQCN you may be on the safe side in most cases. But even if you do so it is not granted, that this name is not already in use.

Tests to make sure that your choice is unique would be required for your code. This tests need to be repeated everytime you add a new module, because what was unique the first time can be changed because of the additional config. 

ServiceManager could grant the uniqueness of a name. The risk of unwanted side effects caused by name duplication (which means overwriting in aggregated configs) could get eliminated completely.

You already have to store and pass a service name (you defined) around. So the only difference would be store another name. Which is granted to be unique now and in the future (when you may add modules or such).

**Comment by kynx** [comment]
Well I’ve never had problems with service name collisions, so maybe I should keep quiet on this one. But I just don’t see why you need to get $handle from the SM again when you’ve already got $myService. 

Running tests after doing something as major as adding a module is exactly what people should do.

**Comment by fhein** [comment]
In your scenario (passing around $myService) why would you call setService at all? You already have $myService. I am not quite sure, what you are asking.

In your scenario the feature requested here does not apply. SM's setService API does not apply.

**Comment by weierophinney** [comment]
This is not a feature we want to incorporate.

The correct ways to override services are:

- Using configuration, where configuration merging allows a fine-grained approach to override services, but only configure the container _once_.
- By setting the "allow override" flag prior to injecting a service. Since services may have been retrieved prior to an injection operation, this approach signals to the developer that they are introducing a state change that may lead to desynchronization (i.e., retrieving a service by the indicated name now may retrieve a different instance than prior to the operation).

Further, introducing multiple behaviors for a method is problematic from both a maintenance and a documentation point of view. From the maintenance side, we now have more vectors for potential bugs to be introduced. From the documentation side, we now have multiple behaviors to document, and the contexts in which each is in play. Our experience with this is that the more behaviors, the harder it is for developers to use the component. Our efforts over the past couple years have been towards _reducing_ behaviors.

If you really need this feature, extend the class and/or introduce a new method.

**Comment by fhein** [comment]
I understand and agree. This feature is somewhat spooky.

Anyway, I found that 'multiple behaviours for a method' technique in the current implementation.

    /**
     * Add an invokable class mapping.
     *
     * @param string $name Service name
     * @param null|string $class Class to which to map; if omitted, $name is
     *     assumed.
     */
    public function setInvokableClass($name, $class = null)

**Comment by weierophinney** [comment]
> I found that 'multiple behaviours for a method' technique in the current implementation. So I assumed once more, that was ok.

Like all developers, our understanding of code, and, particularly, _maintenance of code_, improves over time. As we accept new patches, we're looking at pain points of maintenance, and discouraging patches that would introduce pain points that can be avoided. This is one of those situations. Adding additional behaviors and paths to a signature is a pain point.

**Comment by fhein** [comment]
Ok. I comprehend. But please acknowledge that I am trying to do the things in a way that is already established. There are details which I simply can not know. Thanks for clarification.

It can happen, that I propose or do things wrong for the same reason in the future. Don't assume malice, please. I do may best to respect and adopt the prevalent style.
