### ISSUE TITLE
Question: Exception safety

### ISSUE THREAD

**Issue by fhein** [zendframework/zend-servicemanager#229]
Currently, the service manager is not exception safe. Operations which can throw are not designed to be atomic. Configs may have been partially applied, when the exception occurs.

What, if the user decides to catch all of sm's exception and continue with the sm? Currently he possibly faces partially applied configs which may be but are not granted to be consistent.

It would cost performance to adjust sm such that the user could continue with the last known valid configuration after an exception.

What about a consistency check, which the user could explicitly trigger after he caught an exception. This consistency check would be costly, but it could dispose any invalid configuration. The resulting config be a partially application of the config which caused the exception, but it would be valid.

Please advice.

**Comment by Xerkus** [comment]
I consider bad configuration exceptions as a bug to be caught by integration testing and fixed.
As for the configuration trying to override existing entries, doesn't it already check for conflicts before actually applying config?

**Comment by fhein** [comment]
Not really. It basically checks, if overrides are allowed.

**Comment by Ocramius** [comment]
Ideally, having only __construct to modify the ServiceManager, this should
really only happen at boot time.

As explained before, all other methods come from 2.0.x, and they were
probably added too eagerly, when we didn't yet value mutability as much as
we currently do in the ZF projects.

**Comment by fhein** [comment]
Thinking again about this stuff. I believe, it is in general not a good option, to handle ServiceManager exceptions in userland. This would require intimate knowledge of ServiceManager's internals, which are subject to change.

I close this one.
