### ISSUE TITLE
Tuning lazy_services for production

### ISSUE THREAD

**Issue by Orkin** [zendframework/zend-servicemanager#274]
Hello,

I would like to tune the lazy services with the proxy manager for production. It seems there is a problem because it try to generate proxies again on each request even when they already exist.

https://github.com/Ocramius/ProxyManager/issues/437

Thanks

**Comment by Ocramius** [comment]
@Orkin would need a bit more than that: can this be reproduced in a test scenario, somehow?

**Comment by Orkin** [comment]
Ok so I use the `Service Manager` version `3.3.2` with `Zend Expressive` version `3.0.3`

I have found 2 issues :
The first one in development mode `composer development-enable` and this is my `config/autoload/development.local.php` : 
```php
<?php

declare(strict_types=1);

/**
 * Development-only configuration.
 *
 * Put settings you want enabled when under development mode in this file, and
 * check it into your repository.
 *
 * Developers on your team will then automatically enable them by calling on
 * `composer development-enable`.
 */

return [
...
    'dependencies' => [
        'lazy_services' => [
            // whether the generated proxy classes should be written to disk or generated on-the-fly
            'write_proxy_files' => false,
        ],
    ],
...
];
```
And my `dependencies.global.php` : 
```php
<?php

declare(strict_types=1);

return [
    // Provides application-wide services.
    // We recommend using fully-qualified class names whenever possible as
    // service names.
    'dependencies' => [
        'lazy_services' => [
            // directory where proxy classes will be written - default to system_get_tmp_dir()
            'proxies_target_dir' => \getcwd() . '/data/cache/OcramiusProxy', // in my docker container its /var/www/data/cache/OcramiusProxy

            // namespace of the generated proxies, default to "ProxyManagerGeneratedProxy"
            'proxies_namespace' => null,

            // whether the generated proxy classes should be written to disk or generated on-the-fly
            'write_proxy_files' => true,
        ],
    ],
];
```
The development.local.php `write_proxy_files` config overwrite the `dependencies.global.php` so in development mode the `write_proxy_files` === false

I don't have write and read permission on my folder `/var/www/data/cache/OcramiusProxy` and I have an error here https://github.com/Ocramius/ProxyManager/blob/master/src/ProxyManager/FileLocator/FileLocator.php#L30 I don't know why there is a need of the folder `/var/www/data/cache/OcramiusProxy` to be readable/writable when proxies are generated on the fly and not saved on the disk.

The second problem is in production mode `composer development-disable`, in this case `write_proxy_files` is set to true.
I have a command that write proxies in my folder `/var/www/data/cache/OcramiusProxy`. After the run of the command I can found all my proxies. To be sure there is not read/write problem I tried with `chmod 777 /var/www/data/cache/OcramiusProxy/*`. And on each request file are write in this folder even they are present !

I hope it can help 😃

**Comment by Orkin** [comment]
> This is just checking if the path you configured exists, nothing else.

Ok I understand but it is really necessary to do this check when proxies are generated on the fly ? Because it do not need to exist. I'm agree to the fact to test if the configuration is ok but it can be blocking.

> Seems like autoloading is failing for the proxies. Can you try dumping a proxy class name, then (fresh process) check a class_exists() of it? You may need to run the abstract factory once though.

It return false, it's really strange

**Comment by Ocramius** [comment]
> when proxies are generated on the fly ?

Proxies are always generated on the fly, if they cannot be found. In production, you'd rely on the proxies to already exist.

**Comment by Orkin** [comment]
Hey, I found a solution, there was 2 bugs :
- One one my side about write permissions
- And the second, I write a cli that create proxies on my deployment script.

Thanks

**Comment by Ocramius** [comment]
Could you detail what your CLI script was doing? Would be useful for others
hitting the same issue.

**Comment by Ocramius** [comment]
That command has no body though?

**Comment by Orkin** [comment]
@Ocramius Nop, its an empty command, I found this hack to make it work. This command is loaded by the DI and DI + autoloading create proxies
