### ISSUE TITLE
Merging to master

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-servicemanager#28]
Hey @weierophinney ,

Is there any specific things to do/verify before we can merge that to master ? Would help to try Zend\Expressive with this :)

**Comment by weierophinney** [comment]
I need to complete documentation. ;-)

**Comment by weierophinney** [comment]
Sorry, thought this was the event manager. However, I do want to get full
documentation in here before we do consider a merge to master and/or
initial 3.0 beta or RC.
