### ISSUE TITLE
[Feature Request] Add context binding or something like that

### ISSUE THREAD

**Issue by khuyennguyen7007** [zendframework/zend-servicemanager#284]
I'm using zend service manager to manage my dependencies. In this case, I want to inject params to constructor base on context. Specifically, I have an `SearchManager` class, if in `Application\User\Index`, it will be injected with 2 params, but in `Application\Post\Index`, it will be injected 3 params.

**Comment by froschdesign** [comment]
If I understand your request correctly, then please have a look at method `build` of the `Zend\ServiceManager\ServiceManager` class. All informations can be found in the [documentation](https://docs.zendframework.com/zend-servicemanager/configuring-the-service-manager/#passing-config-to-a-factorydelegator) (direct link).

**Comment by khuyennguyen7007** [comment]
Sorry but it seem like your docs is not what I need. In factory, I can not determine the context where build method invoked (eg: what controller, what module,...). Morever, it seem like factory just allow pass an array options. I need automatic dependency injection on constructor like this:
```
__construct(ClassOne $one, ClassTwo $two) {}
```

**Comment by froschdesign** [comment]
> I need automatic dependency injection on constructor…

Then look at the reflection based factory: https://docs.zendframework.com/zend-servicemanager/reflection-abstract-factory/

**Comment by khuyennguyen7007** [comment]
Like i said, i need two things:
1. Auto dependencies injection. Yes, I can use reflection abstract factory.
2. Context, where class will be got. How do you determine the context to inject an exact number of params.

**Comment by froschdesign** [comment]
@khuyennguyen7007 
> Context, where class will be got.

The context is provided by the parameter `$requestedName`.

**Comment by froschdesign** [comment]
@khuyennguyen7007 
I will provide a code example.

**Comment by froschdesign** [comment]
@khuyennguyen7007 
The context is provide by the parameter `$requestedName`.
The example shows the usage of the parameter in the factory for the controllers.

```php
// Factory for controllers
$controllerFactory = static function (
    Psr\Container\ContainerInterface $container,
    $requestedName,
    array $options = null
) {
    switch ($requestedName) {
        case UserController::class:
            $options = [
                'parameter_1',
                'parameter_2',
            ];
            break;

        case PostController::class:
            $options = [
                'parameter_1',
                'parameter_2',
                'parameter_3',
            ];
            break;

        default:
            $options = [];
            break;
    }

    $container->build(SearchManager::class, $options);
};

// Factory for search-manager
$searchManagerFactory = static function (
    Psr\Container\ContainerInterface $container,
    $requestedName,
    array $options = null
) {
    return new class (...$options) {
        public function __construct($param1 = null, $param2 = null, $param3 = null)
        {
            var_dump($param1);
            var_dump($param2);
            var_dump($param3);
        }
    };
};

// Service manager
$serviceManager = new Zend\ServiceManager\ServiceManager(
    [
        'factories' => [
            SearchManager::class  => $searchManagerFactory,
            UserController::class => $controllerFactory,
            PostController::class => $controllerFactory,
        ],
    ]
);

// Get controllers
$serviceManager->get(UserController::class);
$serviceManager->get(PostController::class);
```

_Please do not use this code in production, it's far away from perfect and it's only illustrative material for this issue report._

**Comment by khuyennguyen7007** [comment]
Thank you very much for your sample code. But i'm still stuck in this:
1. `$serviceManager->get(UserController::class)` not return object instance, it's return `null` value.
2. How to combined it with `ReflectionBasedAbstractFactory`. Eg:
```php
class Service {}

class UserController {
    public function __construct(SearchManager $searchManager, Service $service) {
        var_dump($service);
    }
}
```
When `$serviceManager->get(UserController::class);`, it's will automatic injected dependencies and build `SearchManager` as above.

**Comment by webimpress** [comment]
@khuyennguyen7007 

> `$serviceManager->get(UserController::class)` not return object instance, it's return null value.

There is missing `return` statement before `$container->build(SearchManager::class, $options);` in the first function provided by @froschdesign.

> How to combined it with `ReflectionBasedAbstractFactory`. Eg...

I guess you want to use: https://github.com/zendframework/zend-di

**Comment by froschdesign** [comment]
@khuyennguyen7007 
> 1. `$serviceManager->get(UserController::class)` not return object instance, it's return null value.

Right, but this is not needed in _this_ example. Only the output is interesting.

**Comment by khuyennguyen7007** [comment]
Sorry but it's very weird to me. I'm still not understand.
1. `$serviceManager->get(UserController::class)` must be return `UserController` instance for using in my case. Why is it not needed?
2. I discovered an issue in the example above is that build method is just return object in runtime, not save into manager. With this example:
```php
class Service {}

class UserController {
    public function __construct(SearchManager $searchManager, Service $service) {
        var_dump($searchManager);
    }
}
```
`$searchManager` will be null in params.

**Comment by froschdesign** [comment]
@khuyennguyen7007 
> 1. `$serviceManager->get(UserController::class)` must be return `UserController` instance for using in my case. Why is it not needed?

It‘s not needed here on GitHub as example to illustrate the workflow. In real application you need the `return`. The important part of my example is the output from `var_dump`.

(Btw. I already added the missing `return` in the code example above.)

**Comment by khuyennguyen7007** [comment]
After doing some digging. I have founded a solution for this. Something like this:
```php
'factories' => [
            IndexController::class => function ($container, $requestedName, $options) {
                if ($requestedName == IndexController::class) {
                    $options = ['parameter_1', 'parameter_2'];
                    $searchManager = $container->build(SearchManager::class, $options);
                    $container->setAllowOverride(true);
                    $container->setService(SearchManager::class, $searchManager);
                }
                return $container->get($requestedName);
            }
]
```
It's will build `SearchManager` with an exactly number of params what I want and resave it into manager. Moreover, it's will return controller object with automatic constructor injection.
Thank you for helping me to do this. In the past, I forgot that I can use the same factory for multiple service and the `$requestedName` just return the name of service what the same with the key in config array, so I was thinking that is meaningless.

**Comment by froschdesign** [comment]
@khuyennguyen7007 
My example was created for running without extra classes. Maybe that was not clear enough. _Sorry for that!_ 

In a real application you must change this line in the controller factory from:

```php
$container->build(SearchManager::class, $options);
```

to

```
return new $requestedName($container->build(SearchManager::class, $options));
```

**Comment by khuyennguyen7007** [comment]
Thanks for your advice, but I think I should use `get` method instead of `new` keyword for convenience. I like the `ReflectionBasedAbstractFactory` mechanism instead write my own factory for each service.
With your sample, in the future, if I need a service, I must rewrite code in factory and constructor. But with `ReflectionBasedAbstractFactory`, I just focus on constructor.

**Comment by froschdesign** [comment]
> I must rewrite code in factory

The same with your factory: `if ($requestedName == IndexController::class)`

Btw. this won't work in your factory: `return $container->get($requestedName);` – the service-manager will call the factory again.

**Comment by froschdesign** [comment]
@khuyennguyen7007 
I think you found a solution for your application. Can we close this request?

If you have further questions, please use the [official forum](https://discourse.zendframework.com/).

**Comment by khuyennguyen7007** [comment]
I have a last question, like you said

> Btw. this won't work in your factory: `return $container->get($requestedName);` – the service-manager will call the factory again.

But I have tested my example code and it's working properly, the factory just run one time only. Why do you think it recall again?
