### ISSUE TITLE
container-interop abandoned warning 

### ISSUE THREAD

**Issue by albaquarto** [zendframework/zend-servicemanager#286]
container-interop package is deprecated form February 2017. now during the install I receive this warning
"Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead."

When you merge develop branch into master? And remove definitely container-interop dependency?
#245 #187

**Comment by michalbundyra** [comment]
@albaquarto See: https://github.com/zendframework/zend-eventmanager/issues/79#issuecomment-562228837

The same applies here.
