### ISSUE TITLE
Service manager captures exceptions thrown by Factories

### ISSUE THREAD

**Issue by jeanCarloMachado** [zendframework/zend-servicemanager#32]
This is not necessarily an problem, but the fact that service manager captures exceptions thrown by Factories makes it harder to debug, and hard to treat them as well. I would suggest that, as an improvement, we remove the mechanism of catching these exceptions letting the programmer free to treat them as it pleases him.

If there is some constraint or business rule I'm missing, please let me know.

**Comment by weierophinney** [comment]
This is addressed in the refactor currently in the develop branch.

**Comment by jeanCarloMachado** [comment]
Thanks for the quick answer. :)
