### ISSUE TITLE
[v3] Abstract factories for zend-expressive middleware

### ISSUE THREAD

**Issue by acelaya** [zendframework/zend-servicemanager#40]
I'm testing the ServiceManager version 3 in a Zend Expressive application and I'm getting this problem.
Since abstract factories are no longer included while calling `Container::has`, it always returns false.
That makes all my middleware to be lazily instantiated, instead of being fetched from the ServiceManager, producing exceptions due to missing constructor arguments.

**Comment by bakura10** [comment]
There is an optional second parameter for "has" that fetch abstract factories. But the default parameter is not the same. Was true in ZF2, but false in ZF3. Maybe that’s an unnecessary breaking change and we could change it back.

Matthew?

**Comment by Maks3w** [comment]
I prefer prioritize performance over compatibility.

**Comment by weierophinney** [comment]
This is solvable; the has() method (in v3) allows passing a flag to tell it
to query abstract factories. Do you want to open a PR for this, or shall I?

**Comment by acelaya** [comment]
Sure, I can open the pull request.
The only thing that needs to be done is adding the second argument when internally calling the `has` method in zend expressive, right?

**Comment by weierophinney** [comment]
Correct! Thanks in advance!

**Comment by acelaya** [comment]
Just opened the PR.
https://github.com/zendframework/zend-expressive/pull/156
