### ISSUE TITLE
Thrown exceptions don't implement the container-interop interfaces

### ISSUE THREAD

**Issue by zerocrates** [zendframework/zend-servicemanager#45]
The latest version of the ServiceManager advertises that it implements the container-interop interface, but it doesn't follow the spec rules on exceptions:

>Exceptions directly thrown by the container MUST implement the `Interop\Container\Exception\ContainerException`.
>
> A call to the get method with a non-existing id SHOULD throw a `Interop\Container\Exception\NotFoundException`.

**Comment by Maks3w** [comment]
Can you provide a proof of violation? Did you verify the code on `develop` branch?

**Comment by weierophinney** [comment]
This is definitely fixed on the develop branch; I'm not 100% certain on the master branch.

@zerocrates — would you be willing to create a PR for the master branch?

**Comment by zerocrates** [comment]
Yes, to clarify, I'm talking about the master branch.

I can make a pull request if you'd like.
