### ISSUE TITLE
canonicalizeName(): use str_replace instead of strtr function

### ISSUE THREAD

**Issue by Colmea** [zendframework/zend-servicemanager#57]
Hello,

After profiling my zf2 app, I saw that strtr() function in ServiceManager::canonicalizeName() was a little bit "too expensive": 3.41MB memory (48% of the memory used), almost 4ms CPU time (5% of the total time).
strtr function is actually called 500 times (in my app) from canonicalizeName method.

After some tests, it seems that str_replace function is far more efficient than strtr (in this particular case at least): 132KB for memory and 704µs for CPU time.

I'm not a suporter of "over-optimization", but I think this little enhancement could be interesting

I can create a PR if you want.

#### My app
Benchmark on a working zf2 app (499 services use the *strtr* function).

<img src="https://box.everhelper.me/attachment/343693/uCmUcdQtHYtrtMyLtACNK5r5XzgC2WmN/528539-CqrFXxEUTtCRqJQ1/screen.png" width="100" /> **VS** <img src="https://box.everhelper.me/attachment/343709/uCmUcdQtHYtrtMyLtACNK5r5XzgC2WmN/528539-pitzUfPlRbwe59Mx/screen.png" width="100" />

#### strtr() vs str_replace()
Isolated benchmark of str and str_replace functions. Almost 4 millions iterations. Use services string from existing zf2 app.

<img src="https://box.everhelper.me/attachment/343845/uCmUcdQtHYtrtMyLtACNK5r5XzgC2WmN/528539-ckphAUQb6OpmZQ8H/screen.png" width="100" /> **VS** <img src="https://box.everhelper.me/attachment/343846/uCmUcdQtHYtrtMyLtACNK5r5XzgC2WmN/528539-zEVUc3ugC08GpQTH/screen.png" width="100" />

----

Arthur Schwaiger

**Comment by Maks3w** [comment]
The first example is not conclusive because one method was called half of times than other. So seems to be a comparison with different scenarios.

Please send a PR with your proposal and we'll review if its safe to make that replacement.

**Comment by Colmea** [comment]
Yep, my bad. The screenshot is not good. Actually the 3.8ms are 95% used by strtr() from canonicalizeName() method.

I will send a PR :)

**Comment by Ocramius** [comment]
Interesting... I remember removing str_replace and using strtr for similar
(opposite) reasons. Did PHP just get better at it?

**Comment by Maks3w** [comment]
This benchmark http://micro-optimization.com/strtr-vs-str_replace.html and this other https://3v4l.org/13N5N show different results for same PHP versions (first one look to be executed in a Mac platform)

And here there is an advice about possible secondary effects http://stackoverflow.com/questions/8177296/when-to-use-strtr-vs-str-replace

**Comment by Colmea** [comment]
@Maks3w Actually I use the same code for the second benchmark. Except that I give two arrays (with all services names and all chars to replace): maybe that's the difference.

See these gists used for the second benchmark: 
strtr(): https://gist.github.com/Colmea/3d7d73efaef493e1a6ab
str_replace(): https://gist.github.com/Colmea/d191cc512cfd93a9ee24

Maybe you could test it on your own server ?

Regarding secondary effects, it only happens when one char in the *to* array is also in the *from* array. That's not a problem for us since, in the end, we only want to remove these chars.

About that, str_replace allow us to avoid the use of an array for the *'to'* param:
`str_replace(array('-', '_', '\\', ...), '', $name);`

That's not possible with strtr, which need the same length for *from* and *to* params.

**Comment by tasmaniski** [comment]
this functionality is removed in ZF3

"In v3, service names are case sensitive, and are not normalized in any way." 
https://github.com/zendframework/zend-servicemanager/blob/develop/doc/book/migration.md#case-sensitivity-and-normalization

**Comment by Colmea** [comment]
@tasmaniski Yes, still useful for v2 :)
About that, how do you manage fixes that you need in v2 but not in v3 ? I have to send a PR in the master branch, right ?

**Comment by weierophinney** [comment]
> About that, how do you manage fixes that you need in v2 but not in v3 ? I have to send a PR in the master branch, right ?

Correct.

**Comment by bakura10** [comment]
Can be closed @Ocramius since v3 has been released.

**Comment by Ocramius** [comment]
Closing as invalid
