### ISSUE TITLE
Add configure() method to 2.8 for easier migration to 3.0

### ISSUE THREAD

**Issue by sandrokeil** [zendframework/zend-servicemanager#65]
It would be useful for libraries to have a support for version >= 2.7 und >= 3.0. For this I need a `configure()` method so i can use it for version 2.8 and 3.0, because the [constructor](https://github.com/zendframework/zend-servicemanager/blob/release-2.7.2/src/ServiceManager.php#L129 "2.x constructor") has [changed](https://github.com/zendframework/zend-servicemanager/blob/master/src/ServiceManager.php#L137 "3.x constructor").

I can not do this `return new ServiceManager(new Config(require 'config/dependencies.php'));` in my services.php in 3.0.

For example for SM 2.8

```php
    public function configure(array $config)
    {
        $config = new Config($config);
        $config->configureServiceManager($this);
    }
```

What do you think?

**Comment by gianarb** [comment]
It is less **S**olid
In my opinion it is not a good practice

**Comment by sandrokeil** [comment]
Is there another way to support both versions. With the great migration path to ServiceManager v3, this is the only thing i missed. Btw [ServiceManager v3 has the configure() method too](https://github.com/zendframework/zend-servicemanager/blob/master/src/ServiceManager.php#L299).

**Comment by weierophinney** [comment]
Adding more forwards-compat features adds to the maintenance burden for 2.X. Since we already have a migration path for ensuring you can configure a ServiceManager instance for either v2 or v3, I see no need to add to that.
