### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by pine3ree** [zendframework/zend-servicemanager#70]
Hello,

many invokables are likely to be configured like this:
```php
[
    //....
    'invokables' => [
        //....
        My\Name\Space\ClassName::class => My\Name\Space\ClassName::class,
        //....
    ],
    //....
]
``` 

wouldn' it be useful to be able to define just 1 string value in the configuration array and handle cases when $name type is integer (by setting $name = $class) in ServiceManager::createAliasesForInvokables(), ServiceManager::createFactoriesForInvokables()?

kind regards

**Comment by weierophinney** [comment]
@pine3ree — there are a number of reasons for using key/value pairs, but the most compelling one is that it allows using a service name different than the class name itself. In v3, we make this explicit: invokables defined that way actually become two separate entries:

- a factory with the name being the class, using the `InvokableFactory`
- if the key differs from the value, then that is used to alias the key to the class name.

In other words, in your above example, as of v3, internally it will be rewritten to the following:

```php
[
    'factories' => [
        My\Name\Space\ClassName::class => Zend\ServiceManager\Factory\InvokableFactory::class,
    ],
]
```

If you had defined it as `'classname' => My\Name\Space\ClassName::class`, internally it becomes:

```php
[
    'aliases' => [
        'classname' => My\Name\Space\ClassName::class,
    ],
    'factories' => [
        My\Name\Space\ClassName::class => Zend\ServiceManager\Factory\InvokableFactory::class,
    ],
]
```

As such, in v3, *we no longer recommend using invokables definitions*, in favor of explicitly defining class/`InvokableFactory` + (optional) alias/class pairs as shown above. Doing so is preferred for a number of reasons:

- First, it's what happens internally anyways.
- Second, using the `InvokableFactory` provides some internal performance optimizations.
- Third, aliases then become optional functionality; internally, we have optimizations with alias resolution that make this process faster.
- Fourth, it makes switching to a factory later a matter of simply changing the factory value (vs. removing an invokable definition and creating a factory defintion).
- Fifth, as of 2.7.3, you can do this in your code targeting v2, and have it work in v3!

**Comment by pine3ree** [comment]
@weierophinney 
Thanks for all the explainations.
By the way, maybe i wasn't very clear in my request, i intended it as an extra/shorter way to define invokables in cases when alias and class are the same, I surely wasn't asking to remove aliases from invokables configuration. :-)
Thanks for the advice about using InvokableFactory, i will look into that.

kind regards
