### ISSUE TITLE
zendframework/zend-stdlib should be required in composer.json

### ISSUE THREAD

**Issue by webimpress** [zendframework/zend-servicemanager#73]
library `zendframework/zend-stdlib` should be required in `composer.json` because it is used in class `Zend\ServiceManager\Config`, and for example running unit tests gives a fatal error:

`PHP Fatal error:  Class 'Zend\Stdlib\ArrayUtils' not found in ...\zend-servicemanager\src\Config.php on line 62`

**Comment by weierophinney** [comment]
Reported in #68.
