### ISSUE TITLE
Misconfigured aliases can trigger an infinite loop during resolution

### ISSUE THREAD

**Issue by stof** [zendframework/zend-servicemanager#83]
While looking at the changes done in the 3.0.2 release (I like looking at the diff when a release is announced with a perf improvement), I saw that ``resolveAliases`` can very easily lead to an infinite loop. It is just a matter of creating circular aliases (which can easily happen by mistake): https://github.com/zendframework/zend-servicemanager/blob/379ebd59434e692341e14e97b356e000aeda7ae4/src/ServiceManager.php#L574

```
$config['aliases'] = [
    'a' => 'b',
    'b' => 'a',
]
```

On a side note, I don't understand why the method receives the aliases as argument, while still accessing the property (containing the same array) internally.

**Comment by kynx** [comment]
sm3 is brittle when it comes to infinite loops. Try doing a `$container->has('config')` inside an `AbstractServiceFactoryInterface::canCreate()` :|

But it's fast. Configuration and coding errors _should_ bomb code. It's just a question about how obscure the error is. Maybe a debug mode that throws an exception telling you what you're doing wrong would be a good idea. You'd want to turn it off in production, though.

My two pence.

**Comment by Ocramius** [comment]
@stof ouch, nice catch. Indeed, if this was done via recursion, at least it would crash...

**Comment by Ocramius** [comment]
A quick solution to this is to implement something like the `$visited` array (used by [doctrine's `UnitOfWork`, for example](https://github.com/doctrine/doctrine2/blob/a4d84e0cd8cc4ea1b99f4fd7d1d560f3fbe27c30/lib/Doctrine/ORM/UnitOfWork.php#L1647)) to prevent invinite loops.

**Comment by kynx** [comment]
@Ocramius  Or just a simple counter that throws exception after 100 iterations?

**Comment by stof** [comment]
@kynx even though it would be weird, a very long list of aliases is not broken. But a circular one is. This is the case which should be detected if possible.

**Comment by Ocramius** [comment]
Much simpler, to be honest. I'll write a test asap :-)

**Comment by Ocramius** [comment]
Provided a fix with minimal performance regressions in #89
