### ISSUE TITLE
ServiceManager constructor arg

### ISSUE THREAD

**Issue by jsoumelidis** [zendframework/zend-servicemanager#94]
Copying from the online documentation:

**ServiceManager API Changes
Configuration no longer requires a Zend\ServiceManager\Config instance.  Config can be used, but is no needed.**

While constructor source code **requires** an array as 1st argument and it breaks migration.

**Comment by weierophinney** [comment]
@jsoumelidis Notice that this is for version 3; BC breaks are expected in new major versions!

The migration path is to do the following:

```php
use Zend\ServiceManager\Config;
use Zend\ServiceManager;

$services = new ServiceManager();
$config = new Config($serviceConfigurationArray);
$services = $config->configureServiceManager($services);

// OR
$config = new Config($serviceConfigurationArray);
$services = $config->configureServiceManager(new ServiceManager());
```

Updating  your code to either of the above makes it compatible with either version. Once you are using strictly v3, you can update it to more simply read:

```php
$services = new ServiceManager($serviceConfigurationArray);
```

**Comment by jsoumelidis** [comment]
Ofc, thanks for the tip. It's just that documentation doesn't make it clear :)
