### ISSUE TITLE
Are the badges wrong?

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-servicemanager#99]
The coverage badge says that master is tested at 78% while develop is 99%. But now that v3 is merged, the master should be also at 99%.

I'm not really sure why the badge is incorrect though.

**Comment by weierophinney** [comment]
Honestly, no clue; probably a problem with coveralls.

**Comment by svycka** [comment]
https://github.com/zendframework/zend-servicemanager/pull/98

**Comment by samsonasik** [comment]
@bakura10 it fixed now by @svycka at #98 , close-able.

**Comment by samsonasik** [comment]
it can be closed in favor of #98
